[AR-010] Create pagination for products list. Add url and fetch url change logic
sspr/allegro-rolnik pull request #10
Opened 2022-01-18 08:00 UTC by sspr

2022-01-18 17:19 UTC, szumike requested changes

2022-01-18 17:19 UTC, szumike commented on src/app/components/product/productsList/ProductsListContainer.types.ts
> +  setProductsCount: (productsCount: number | undefined) => void | undefined;
Pamiętasz jak rozmawialiśmy o tym, że nazwy komponentów powinniśmy nazywać z perspektywy komponentu w oderwaniu od kontekstu w jakim jest użyty? W takim razie, jak poprawnie powinien się nazywać ten props?

2022-01-18 17:19 UTC, szumike commented on src/hooks/useFetch/useFetch.ts
> +export const useFetch = <TResponse>(url: string | undefined, queryParams?: QueryParams): FetchResult<TResponse> => {
Zauważ - na ten moment `useFetch` przestał być generyczny (czyli do użytku do każdego zapytania), ponieważ można nim fetchować tylko dane, które mają na response dwa pola: `meta` i `data`. Ten hook powinien nie być w ogóle ruszany. Chyba że nazwalibyśmy go `useFetchMetaAndData` (co nie jest najszczęsliwszym rozwiązaniem).
**Note:** Zwróć uwagę na nazewnictwo - na tym polega pisanie dobrego, samokomentującego się kodu, tzn że nazwy odzwierciedlają co robi dana funkcja / co reprezentuje dana zmienna.
Zamiast tego, ten hook ma zwracać dokładnie takie dane, jakie dostał z API (czyli `{ meta: ..., data: ... }`). Czyli wywołanie `useFetch` powinno wyglądać tak: 
```
... = useFetch<ProductResponse>(...
```
gdzie `ProductResponse` z pliku `src/api/product/product.types.ts`:
```
type ProductResponse = {
  meta: {
    count: number;
  };
  data: Product[];
}

2022-01-18 17:19 UTC, szumike commented on src/ui/pagination/Pagination.tsx
> +    for (let i = 1; i < productsCount / 15 + 1; i++) {
Staramy się nie pisać kodu w tak imperatywny sposób (poczytaj co to znaczy). Spróbuj od raz u 12 linii przypisać odpowiednią wartość używając bardziej deklaratywnego podejścia (np tak: https://stackoverflow.com/questions/3746725/how-to-create-an-array-containing-1-n)

2022-01-18 17:19 UTC, szumike commented on src/ui/pagination/paginationLink/PaginationLink.types.ts
> +  card: number;
Czym jest `card`? Ta nazwa jest jakaś niezrozumiała

2022-01-18 17:19 UTC, szumike commented on src/ui/pagination/paginationLink/PaginationLink.tsx
> +  const { updateQueryParams } = useUrl();
Zauważ, że ten komponent jest nietestowalny, przez to, że wewnątrz niego wyciągamy jakieś dane z niewiadomo skąd.
Żeby był testowalny, wszystkie wartości, które "sterują" komponentem muszą być dostarczone przez propsy z zewnątrz. Pamiętaj, żeby nazwać te propsy z perspektywy tego komponentu

2022-01-18 17:19 UTC, szumike commented on src/ui/pagination/Pagination.tsx
> +export const Pagination = ({ productsCount }: PaginationProps) => {
Dwie rzeczy:
1. Wyobraź sobie, że masz apkę, która ma więcej niż jedno miejsce z paginacją, powiedzmy listę zakupów. Wtedy za cholerę nie nazwa `productsCount` pasować do nowej strony (bo musiałby się nazywać `purchasesCount`). Więc albo nazwiemy ten komponent `ProductPaginator`, albo zmienimy tego propsa.
2. Właściwie `Pagination` jest nietestowalny ze względu na użycie wewnątrz `useUrl`. W testach poradziłeś sobie z tym całkiem nieźle, niemniej żeby on był naprawdę testowalny i reużywalny w innych miejscach aplikacji, zmień cały komponent tak, żeby miał tylko trzy propsy:
```
type PaginationProps = {
  pageCount: number;
  currentPage: number;
  onPageClick: (page: number) => void;
}
```

2022-01-18 17:19 UTC, szumike commented on src/ui/pagination/Pagination.tsx
> +export const Pagination = ({ productsCount }: PaginationProps) => {
**Pro tip:** zanim zaczniesz implementować jakieś ogólne komponenty, zacznij od zdefiniowania, jakie mają mieć propsy, dopiero do nich implementuj bebechy komponentu

2022-01-18 17:19 UTC, szumike commented on src/app/components/product/productsList/ProductsListContainer.tsx
> +  const { data, isLoading, isError, meta } = useFetch<Product[]>(process.env.REACT_APP_API_URL, queryParams);
Zamiast wrzucać `queryParams` tutaj, lepiej mieć funkcje, która wygeneruje konkretnego urla. W takim przypadku w `src/api/product/product.ts` stworzyć
```
const createGetProductsUrl = (params: GetProductsUrlParams): string => ...
```
gdzie `GetProductsUrlParams` będzie miał te parametry paginacji.
To jest o tyle korzystne, że w przypadku bardziej skomplikowanych zapytań (lub updatów istniejących danych w API) mamy dodatkową warstwę abstrakcji, w której możemy modyfikować dane z apki do istniejącego kontraktu z REST API.

2022-01-20 10:03 UTC, szumike requested changes

2022-01-20 10:03 UTC, szumike commented on src/api/product/product.ts
> +    // window.history.pushState(null, document.title, `?${searchParams.toString()}`);
To jest chyba do wyrzucenia, prawda?

2022-01-20 10:03 UTC, szumike commented on src/api/product/product.ts
> +export const createGetProductsUrl = (params: GetProductsUrlParams): string => {
Dobrze byłoby dopisać do tego testy :)

2022-01-20 10:03 UTC, szumike commented on src/hooks/useFetch/useFetch.ts
> +        if (!url && !(url === '')) {
Tam powyżej jest, że `url` może przyjmować wartość undefined. Czy na pewno możemy coś takiego dopuścić? Czy może lepiej dać, że url może być tylko stringiem?

2022-01-20 10:03 UTC, szumike commented on src/api/product/product.ts
> +  const url = new URL(window.location.href);
Trochę nie rozumiem, po co to jest...
Z tej funkcji powinna wychodzić część urla, która będzie wyglądać mniej więcej tak: `/machines?page=3&perPage=10`. Potem w `useFetch` ma być doklejona część hostowa pobrana z envów. Tak to aktualnie działa?

2022-01-20 10:03 UTC, szumike commented on src/context/urlParams/defaultUrlParams.ts
> +export const defaultUrlParams = { page: 1, perPage: 15 };
A nie miało być 10?

2022-01-20 10:03 UTC, szumike commented on src/ui/pagination/Pagination.test.tsx
> +});
Można dopisać jeszcze testy odnośnie klikania w pages :)

2022-01-20 10:03 UTC, szumike commented on src/ui/pagination/Pagination.types.ts
> +  onPageClick: (page: GetProductsUrlParams) => void;
To może być tylko `number`, prawda?

2022-01-20 10:03 UTC, szumike commented on src/ui/pagination/paginationLink/PaginationLink.types.ts
> +  onClick: () => void;
`VoidFunction`

2022-01-20 10:03 UTC, szumike commented on src/context/urlParams/urlParamsContextController/UrlParamsContextController.tsx
> +export const UrlParamsContextController = ({ children }: UrlParamsContextControllerProps) => {
Może to nazwać `ProductParamsContextController`? Jest bardziej domenową nazwą

2022-01-20 12:22 UTC, szumike requested changes

2022-01-20 12:22 UTC, szumike commented on package.json
> +    "use-query-params": "^1.2.3",
Widzę, że dodałeś trzy nowe libki. A faktycznie korzystasz ze wszystkich trzech?

2022-01-20 12:22 UTC, szumike commented on src/app/components/product/productsList/ProductsList.types.ts
> +export type ProductsListContianerProps = {
A tu masz literówkę ;)

2022-01-20 12:22 UTC, szumike commented on src/app/components/product/productsList/ProductsListContainer.tsx
> +  const { data, isLoading, isError } = useFetch<ProductResponse>(`machines?${stringify(productsUrlParams)}`);
A tu kiedyś była funkcja `createGetProductsUrl`, dlaczego zniknęła?

2022-01-20 12:22 UTC, szumike commented on src/hooks/useFetch/useFetch.ts
> +        if (!url && !(url === '')) {
Dalej `url` może być równy `undefined`, dobrze by to było, żeby mógł przyjąć tylko wartość `string`

2022-01-20 12:22 UTC, szumike commented on src/ui/pagination/Pagination.test.tsx
> +  it('renders one actvie link', () => {
literówka

2022-01-20 12:22 UTC, szumike commented on src/ui/pagination/Pagination.test.tsx
> +  it('renders links that are clickable', () => {
Właściwie tutaj sprawdzasz nie tyle renderowanie, ale wywoływanie callbacka `onPageClick`, także można tu napisać `runs callback on click correctly`

2022-01-20 12:25 UTC, sspr commented on package.json
> +    "use-query-params": "^1.2.3",
Tak - use-query-params odpowiada za hooka i wymaga pozostałych dwóch

2022-01-20 12:29 UTC, sspr commented on src/app/components/product/productsList/ProductsListContainer.tsx
> +  const { data, isLoading, isError } = useFetch<ProductResponse>(`machines?${stringify(productsUrlParams)}`);
Bo zastąpiła ją stringify, która zmienia `productsUrlParams` otrzymane z hooka na `stringa`

2022-01-20 13:19 UTC, szumike approved these changes

2022-01-20 13:21 UTC, merged