[AR-005] Create app header
sspr/allegro-rolnik pull request #4
Opened 2022-01-04 08:22 UTC by sspr

2022-01-04 12:20 UTC, szumike requested changes

2022-01-04 12:20 UTC, szumike commented on react-app.d.ts
> +declare module '*.svg' {
Można by to wrzucić do wspólnego folderu `src/types`.
I sam plik mógłby być też bardziej obrazowy, czego to dotyczy, np `svg.d.ts`

2022-01-04 12:20 UTC, szumike commented on src/app/App.test.tsx
> +// test('renders learn react link', () => {
Taka sugestia na przyszłość - lepiej nie commitować zakomentowanego kodu, to wygląda naprawdę źle :) Zamiast tego lepiej usunąć cały plik. Zawsze możesz do niego wrócić używając gita

2022-01-04 12:20 UTC, szumike commented on src/app/componments/header/Header.styles.ts
> +  @media (max-width: 768px) {
Szerokości media możnaby wrzucić theme

2022-01-04 12:20 UTC, szumike commented on src/app/componments/header/Header.tsx
> +          <Button type="submit">search</Button>
Te wszystkie stringi dobrzeby było wyciągać już z `formatMessage`

2022-01-04 12:20 UTC, szumike commented on src/app/componments/header/Header.tsx
> +              hasBorder={index < appLocaleValues.length - 1 ? true : false}
Taaaak, a nie wystarczy samo `index < appLocaleValues.length - 1`? :D

2022-01-04 12:20 UTC, szumike commented on src/app/componments/header/LocaleButton.styles.ts
> +export const LocaleButton = styled.button<{ theme: Theme }>`
Jeśli masz kilka razy wyciągnięcie różnych rzeczy z theme, to można użyć składni funkcyjnej z funkcją `css`: 
```
... = styled.button<{ theme: Theme }>({ theme: { fontSize, color }) => css`
  tutaj wszystkie style
`
```

2022-01-04 12:20 UTC, szumike commented on src/app/componments/header/LocaleButton.tsx
> +  return (
Na przyszłość - jeśli masz funkcję, która zwraca tylko komponent bez dodatkowej logiki, to można to zapisać bardziej skrótowo:
```
export const LocaleButton = ({ localeButtonValue, hasBorder }: LocaleButtonProps) => (
  <>
    ...
  </>
);

2022-01-04 12:20 UTC, szumike commented on src/app/componments/header/Header.tsx
> +export const Header = () => {
Myślę że `Header` jest na tyle globalny, że można gow rzucić do `src/ui`

2022-01-04 12:20 UTC, szumike commented on src/app/componments/header/LocaleButton.types.ts
> +export type LocaleButtonProps = { localeButtonValue: AppLocale; hasBorder: true | false };
Dobrze by było, żeby te poszczególne typy propsów występowały w osobnej linii. To ułatwia czytanie kodu.
Możliwe, że będzie trzeba poszukać odpowiedniego konfiga w prettierze/eslint

2022-01-04 12:20 UTC, szumike commented on src/ui/button/Button.styles.ts
> +  color: #fff;
Kolorek bierzemy z theme kolorków ;)

2022-01-04 12:20 UTC, szumike commented on src/ui/input/Input.types.ts
> +  placeholder: string;
Taki globalny input mógłby mieć trochę więcej propsów (value, onChange itd). Poszukaj w necie, czy jest jakiś sposób, żeby wykorzystać coś już instniejącego (HTMLProps)

2022-01-04 12:34 UTC, szumike commented on src/app/componments/header/Header.tsx
> +            <LocaleButton
Można by tutaj już podpiąć zmianę języka, co nie?

2022-01-04 13:36 UTC, sspr commented on src/app/componments/header/Header.tsx
> +              hasBorder={index < appLocaleValues.length - 1 ? true : false}
Co ja tu odwalam czasami xD

2022-01-05 11:01 UTC, szumike requested changes

2022-01-05 11:01 UTC, szumike commented on src/ui/header/Header.tsx
> +import { Button } from 'ui/button/Button';
Wiesz co, jeśli coś jest ciągnięte lokalnie (z tego samego głównego folderu), to dobrze byłoby to pokazać przez ścieżki bezpośrednie, tzn `../input/Input` itd

2022-01-05 11:01 UTC, szumike commented on src/ui/header/LocaleButton.tsx
> +export const LocaleButton = ({ text, hasBorder }: LocaleButtonProps) => {
Staramy się nie trzymać wielu komponentów w jednym folderze. `LocaleButton` jest stricte związany z headerem i bardzo dobrze że jest tutaj (tzn przy headerze). Niemniej w takiej sytuacji dobrze jest zrobić osobny folder na ten komponent, tj `src/ui/header/localeButton/LocaleButton.tsx`

2022-01-05 11:01 UTC, szumike commented on src/ui/header/LocaleButton.tsx
> +      {hasBorder ? ' | ' : null}
Wiesz co, właściwie to nie jest `boarder`, to jest `separator`. I nie jest on integralną częścią tego komponentu, prawda? Lepiej go wyciągnąć do Headera

2022-01-05 11:01 UTC, szumike commented on src/ui/input/Input.styles.ts
> +export const Input = styled.input<{ theme: Theme }>`
Tak patrzę, widzę że kilka razy użyłeś tej konwencji (to jest wrzucanie `{ theme: Theme }` jako generyka). A wiesz po co to jest? I czy to jest faktycznie dobrze użyte? 😈
Druga sprawa - `styled-components` można użyć tak, żeby TS Ci podpowiadał jakie ma wartości. Poczytaj sobie to: https://dev.to/rajuashok/create-styled-d-ts-to-make-typescript-work-with-styled-components-5dk4

2022-01-05 11:01 UTC, szumike commented on src/ui/button/Button.types.ts
> +  type: 'submit';
Wiesz to, to jest trochę dziwne. Zapis z trzeciej linii de facto znaczy - komponent `Button` zawsze ma mieć props `type`, który zawsze ma przyjmować wartość `submit` xD
W przypadku `Button`a, tak jak w przypadku `Input`a, warto się zastanowić, jak dodać wszystkie jego propsy

2022-01-05 11:01 UTC, szumike commented on src/assets/styles/theme.types.ts
> +  width: {
Wiesz co, ja bym to jednak nazwał `mobile`, `width` jest trochę zbyt ogólne

2022-01-05 11:30 UTC, szumike commented on src/ui/header/Header.tsx
> +  const handleChangeLanguage = (event: React.MouseEvent): void => {
Szłoby to zrobić jako handler, który zawsze jest wykonywany na onclicku buttona

2022-01-05 12:26 UTC, sspr commented on src/assets/styles/theme.types.ts
> +  width: {
Nazwałem to w ten sposób, bo wiem, że jeszcze mam w sidebarze drugą szerokość. Może lepiej 
`screenResolution:{
  mobile:string;
}`

2022-01-10 11:17 UTC, szumike approved these changes

2022-01-10 11:17 UTC, szumike commented on src/assets/styles/styled.d.ts
> +import {} from 'styled-components';
Definicje wszystkich typów globalnych powinny się znajdować w jednym folderze, np `src/types`. Chodzi o to, żeby potem szukając jakiś elementów można było łatwo wiedzieć gdzie to jest, a nie szukać po folderach

2022-01-10 11:17 UTC, szumike commented on src/ui/header/localeButton/LocaleButton.tsx
> +    <>
Ten partial chyba nie jest potrzebny, prawda? :)

2022-01-10 11:17 UTC, szumike commented on src/ui/header/localeButton/LocaleButton.tsx
> +  const { locale } = useLocale();
Zauważ, że komponent `LocaleButton` jest w tym przypadku zależny od zewnętrznego hooka. Jeśli chciałbyś go przetestować, czy dobrze wyświetla się `active`/`not-active`, wtedy musiałbyś mocować całego hooka.
Lepszym rozwiązaniem byłoby, żeby komponent dostawał w propsach tę wartość jako `isActive` (bo jego parent i tak wywołuje `useLocale`)

2022-01-10 19:23 UTC, merged